-- Section 13 - Working with DDL Statements

-- REQUIREMENT: Create tables using the attached ERD. Be sure to include the appropriate data types
-- REQUIREMENT: Rental date should default to the sysdate

-- CUSTOMERS Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(10),
    LAST_NAME VARCHAR2(25),
    FIRST_NAME VARCHAR2(25),
    HOME_PHONE VARCHAR2(12),
    ADDRESS VARCHAR2(100),
    CITY VARCHAR2(30),
    STATE VARCHAR2(2),
    EMAIL VARCHAR2(25),
    CELL_PHONE VARCHAR2(12)
);

-- MOVIES Table
CREATE TABLE MOVIES (
    TITLE_ID NUMBER(10),
    TITLE VARCHAR2(60),
    DESCRIPTION VARCHAR2(400),
    RATING VARCHAR2(4),
    CATEGORY VARCHAR2(20),
    RELEASE_DATE DATE
);

-- MEDIA Table
CREATE TABLE MEDIA (
    MEDIA_ID NUMBER(10),
    FORMAT VARCHAR2(3),
    TITLE_ID NUMBER(10)
);

-- RENTAL_HISTORY Table
CREATE TABLE RENTAL_HISTORY (
    MEDIA_ID NUMBER(10),
    RENTAL_DATE DATE DEFAULT SYSDATE,
    CUSTOMER_ID NUMBER(10),
    RETURN_DATE DATE
);

-- ACTORS 
CREATE TABLE ACTORS (
    ACTOR_ID NUMBER(10),
    STAGE_NAME VARCHAR2(40),
    FIRST_NAME VARCHAR2(25),
    LAST_NAME VARCHAR2(25),
    BIRTH_DATE DATE
);

-- STAR_BILLINGS Table
CREATE TABLE STAR_BILLINGS (
    ACTOR_ID NUMBER(10),
    TITLE_ID NUMBER(10),
    COMMENTS VARCHAR2(40)
);

-- REQUIREMENT: Run a DESC command for each table.
DESC CUSTOMERS;
DESC MOVIES;
DESC MEDIA;
DESC RENTAL_HISTORY;
DESC ACTORS;
DESC STAR_BILLINGS;