-- Section 16 - Working with Sequences (Indexes and Synonyms)

-- REQUIREMENT: Create the following sequences to be used for primary key values:

-- REQUIREMENT: Use a sequence to generate PKs for CUSTOMER_ID in CUSTOMERS table
-- Begin at 101 and increment by 1
CREATE SEQUENCE CUSTOMERS_SEQ
    START WITH 101
    INCREMENT BY 1;

-- REQUIREMENT: Use a sequence to generate PKs for TITLE_ID in MOVIES table
-- Begin at 1 and increment by 1
CREATE SEQUENCE MOVIES_SEQ
    START WITH 1
    INCREMENT BY 1;

-- REQUIREMENT: Use a sequence to generate PKs for MEDIA_ID in MEDIA table
-- Begin at 92 and increment by 1
CREATE SEQUENCE MEDIA_SEQ
    START WITH 92
    INCREMENT BY 1;

-- REQUIREMENT: Use a sequence to generate PKs for ACTOR_ID in ACTOR table
-- Begin at 1001 and increment by 1
CREATE SEQUENCE ACTORS_SEQ
    START WITH 1001
    INCREMENT BY 1;

-- REQUIREMENT: Run queries from the data dictionaries for the above sequences.
SELECT sequence_name, min_value, max_value, increment_by, last_number
FROM user_sequences;

-- REQUIREMENT: Add the data to the tables. Be sure to use the sequences for the PKs.

-- INSERT TO CUSTOMERS
-- "Sample Data – Make up at least 6 members, using the sequence to generate the PKs:"
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUSTOMERS_SEQ.NEXTVAL, 'Palombo', 'Lisa', '716-270-2669', '123 Main St', 'Buffalo', 'NY', 'palombo@ecc.edu', '716-555-1212');

-- Next 6 inserts are AI Generated. For references
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUSTOMERS_SEQ.NEXTVAL, 'Anderson', 'James', '213-234-5678', '123 Maple Street', 'Los Angeles', 'CA', 'james.anderson@email.com', '310-987-6543');

INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUSTOMERS_SEQ.NEXTVAL, 'Martinez', 'Sofia', '512-345-6789', '456 Oak Avenue', 'Austin', 'TX', 'sofia.martinez@email.com', '737-876-5432');

INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUSTOMERS_SEQ.NEXTVAL, 'Chen', 'Michael', '206-456-7890', '789 Pine Road', 'Seattle', 'WA', 'michael.chen@email.com', '425-765-4321');

INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUSTOMERS_SEQ.NEXTVAL, 'Thompson', 'Emily', '305-567-8901', '321 Birch Lane', 'Miami', 'FL', 'emily.thompson@email.com', '786-654-3210');

INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUSTOMERS_SEQ.NEXTVAL, 'Patel', 'Raj', '312-678-9012', '654 Cedar Drive', 'Chicago', 'IL', 'raj.patel@email.com', '773-543-2109');

INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUSTOMERS_SEQ.NEXTVAL, 'Williams', 'Sarah', '617-789-0123', '987 Elm Boulevard', 'Boston', 'MA', 'sarah.williams@email.com', '857-432-1098');

SELECT * FROM CUSTOMERS
ORDER BY CUSTOMER_ID;

-- REQUIREMENT: Run a SELECT * for each table.
-- INSERT INTO MOVIES
-- "Sample Data – Add at least 6 titles, use www.imdb.com for information and the sequence for the PKs:"

INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (MOVIES_SEQ.NEXTVAL, 'Remember the Titans', 'High school football integration drama', 'PG', 'DRAMA', TO_DATE('29-SEP-2000','DD-MON-YYYY'));

INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (MOVIES_SEQ.NEXTVAL, 'Inception', 'A thief steals secrets through dreams', 'PG13', 'SCIFI', TO_DATE('16-JUL-2010','DD-MON-YYYY'));

INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (MOVIES_SEQ.NEXTVAL, 'The Dark Knight', 'Batman battles the Joker', 'PG13', 'ACTION', TO_DATE('18-JUL-2008','DD-MON-YYYY'));

INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (MOVIES_SEQ.NEXTVAL, 'Titanic', 'Romance and tragedy aboard the RMS Titanic', 'PG13', 'DRAMA', TO_DATE('19-DEC-1997','DD-MON-YYYY'));

INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (MOVIES_SEQ.NEXTVAL, 'The Matrix', 'A hacker learns the truth about reality', 'R', 'SCIFI', TO_DATE('31-MAR-1999','DD-MON-YYYY'));

INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (MOVIES_SEQ.NEXTVAL, 'Forrest Gump', 'Life story of Forrest Gump', 'PG13', 'DRAMA', TO_DATE('06-JUL-1994','DD-MON-YYYY'));

SELECT * FROM MOVIES
ORDER BY TITLE_ID;

-- INSERT INTO MEDIA
-- "Sample Data : Use TITLE_ID from the MOVIES table, with one or two copies of each title, using the sequence to generate the PKs:"

INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_SEQ.NEXTVAL, 'DVD', 1);

INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_SEQ.NEXTVAL, 'VHS', 1);

SELECT * FROM MEDIA
ORDER BY MEDIA_ID;

-- INSERT INTO RENTAL_HISTORY
-- "Sample Data – Add 4 rows using MEDIA_ID from the MEDIA table and CUSTOMER_ID from the CUSTOMER table:"

INSERT INTO RENTAL_HISTORY (MEDIA_ID, RENTAL_DATE, CUSTOMER_ID, RETURN_DATE)
VALUES (92, TO_DATE('19-SEP-2010','DD-MON-YYYY'), 101, TO_DATE('20-SEP-2010','DD-MON-YYYY'));

INSERT INTO RENTAL_HISTORY 
VALUES (93, TO_DATE('20-SEP-2010','DD-MON-YYYY'), 102, TO_DATE('22-SEP-2010','DD-MON-YYYY'));

INSERT INTO RENTAL_HISTORY 
VALUES (94, TO_DATE('01-OCT-2010','DD-MON-YYYY'), 103, TO_DATE('03-OCT-2010','DD-MON-YYYY'));

INSERT INTO RENTAL_HISTORY 
VALUES (95, TO_DATE('05-OCT-2010','DD-MON-YYYY'), 104, TO_DATE('08-OCT-2010','DD-MON-YYYY'));

SELECT * FROM RENTAL_HISTORY
ORDER BY MEDIA_ID, RENTAL_DATE;

-- INSERT INTO ACTORS
-- "Sample Data : add at least 4 rows, using the sequence to generate the PKs :"

INSERT INTO ACTORS (ACTOR_ID, STAGE_NAME, FIRST_NAME, LAST_NAME, BIRTH_DATE) 
VALUES (ACTORS_SEQ.NEXTVAL, 'Brad Pitt', 'William', 'Pitt', TO_DATE('18-DEC-1963','DD-MON-YYYY'));

INSERT INTO ACTORS 
VALUES (ACTORS_SEQ.NEXTVAL, 'Leonardo DiCaprio', 'Leonardo', 'DiCaprio', TO_DATE('11-NOV-1974','DD-MON-YYYY'));

INSERT INTO ACTORS 
VALUES (ACTORS_SEQ.NEXTVAL, 'Tom Hanks', 'Tom', 'Hanks', TO_DATE('09-JUL-1956','DD-MON-YYYY'));

INSERT INTO ACTORS
VALUES (ACTORS_SEQ.NEXTVAL, 'Christian Bale', 'Christian', 'Bale', TO_DATE('30-JAN-1974','DD-MON-YYYY'));

SELECT * FROM ACTORS
ORDER BY ACTOR_ID;

-- INSERT INTO STAR_BILLINGS
-- "Sample Data : add at least 4 rows, using ACTOR_IDs from the ACTORS table and TITLE_IDs from the MOVIES table :"

INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS) 
VALUES (1001, 2, 'Supporting Role');

INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS) 
VALUES (1002, 4, 'Lead Actor');

INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS) 
VALUES (1003, 6, 'Lead Actor');

INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS) 
VALUES (1004, 3, 'Villain');

SELECT * FROM STAR_BILLINGS 
ORDER BY ACTOR_ID, TITLE_ID;

-- REQUIREMENT: Create an index on the last_name column of the Customers table.
CREATE INDEX IDX_CUSTOMERS_LAST_NAME ON CUSTOMERS(LAST_NAME);

-- REQUIREMENT: Run a query from the data dictionary for indexes showing this index.
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'LAST_NAME';

-- REQUIREMENT: Create a synonym called TU for the TITLE_UNAVAIL view.
CREATE SYNONYM TU FOR TITLE_UNAVAIL;

-- REQUIREMENT: Run query from the data dictionary for synonyms showing this synonym.
SELECT SYNONYM_NAME, TABLE_OWNER, TABLE_NAME
FROM USER_SYNONYMS
WHERE SYNONYM_NAME = 'TU';

-- REQUIREMENT: Print a SELECT * from the synonym.
SELECT * FROM TU;
