-- Section 16, Task 4: Create Sequences 

-- Sequence for CUSTOMER_ID 
CREATE SEQUENCE CUST_ID_SEQ
START WITH 101
INCREMENT BY 1;

-- Sequence for TITLE_ID 
CREATE SEQUENCE TITLE_ID_SEQ
START WITH 1
INCREMENT BY 1;

-- Sequence for MEDIA_ID 
CREATE SEQUENCE MEDIA_ID_SEQ
START WITH 92
INCREMENT BY 1;

-- Sequence for ACTOR_ID 
CREATE SEQUENCE ACTOR_ID_SEQ
START WITH 1001
INCREMENT BY 1;

-- Query data dictionary for sequences 
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('CUST_ID_SEQ', 'TITLE_ID_SEQ', 'MEDIA_ID_SEQ', 'ACTOR_ID_SEQ');


-- Section 16, Task 5: Add data to tables 
-- We must use the .NEXTVAL function on the sequences for PKs

-- 1. CUSTOMERS (Sample, need at least 6)
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUST_ID_SEQ.NEXTVAL, 'Palombo', 'Lisa', '716-270-2669', '123 Main St', 'Buffalo', 'NY', 'palombo@ecc.edu', '716-555-1212');
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUST_ID_SEQ.NEXTVAL, 'Smith', 'John', '212-555-1234', '456 Wall St', 'New York', 'NY', 'jsmith@gmail.com', '917-555-4321');
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUST_ID_SEQ.NEXTVAL, 'Johnson', 'Jane', '310-555-9876', '789 Ocean Ave', 'Los Angeles', 'CA', 'jane.j@yahoo.com', '310-555-6789');
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUST_ID_SEQ.NEXTVAL, 'Williams', 'Mike', '312-555-5000', '101 Windy Blvd', 'Chicago', 'IL', 'mike.w@aol.com', '312-555-0001');
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUST_ID_SEQ.NEXTVAL, 'Brown', 'Sarah', '713-555-2222', '321 Spacey Rd', 'Houston', 'TX', 'sbrown@nasa.gov', '281-555-1212');
INSERT INTO CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (CUST_ID_SEQ.NEXTVAL, 'Davis', 'Chris', '404-555-1111', '555 Peach St', 'Atlanta', 'GA', 'cdavis@music.com', '404-555-9999');

-- 2. MOVIES (Sample, need at least 6 )
INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, 'Remember the Titans', 'The true story of a newly appointed African-American coach and his high school team...', 'PG', 'DRAMA', TO_DATE('29-SEP-2000', 'DD-MON-YYYY'));
INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption...', 'R', 'DRAMA', TO_DATE('14-OCT-1994', 'DD-MON-YYYY'));
INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, 'The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham...', 'PG13', 'ACTION', TO_DATE('18-JUL-2008', 'DD-MON-YYYY'));
INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, 'Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal...', 'PG13', 'DRAMA', TO_DATE('06-JUL-1994', 'DD-MON-YYYY'));
INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, 'Toy Story', 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure...-','G', 'CHILD', TO_DATE('22-NOV-1995', 'DD-MON-YYYY'));
INSERT INTO MOVIES (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, 'Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'PG13', 'SCIFI', TO_DATE('07-NOV-2014', 'DD-MON-YYYY'));

-- 3. ACTORS (Sample, need at least 4)
INSERT INTO ACTORS (ACTOR_ID, STAGE_NAME, FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES (ACTOR_ID_SEQ.NEXTVAL, 'Brad Pitt', 'William', 'Pitt', TO_DATE('18-DEC-1963', 'DD-MON-YYYY'));
INSERT INTO ACTORS (ACTOR_ID, STAGE_NAME, FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES (ACTOR_ID_SEQ.NEXTVAL, 'Denzel Washington', 'Denzel', 'Washington', TO_DATE('28-DEC-1954', 'DD-MON-YYYY'));
INSERT INTO ACTORS (ACTOR_ID, STAGE_NAME, FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES (ACTOR_ID_SEQ.NEXTVAL, 'Morgan Freeman', 'Morgan', 'Freeman', TO_DATE('01-JUN-1937', 'DD-MON-YYYY'));
INSERT INTO ACTORS (ACTOR_ID, STAGE_NAME, FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES (ACTOR_ID_SEQ.NEXTVAL, 'Tom Hanks', 'Thomas', 'Hanks', TO_DATE('09-JUL-1956', 'DD-MON-YYYY'));

-- 4. MEDIA (Sample, TITLE_ID must match MOVIES)
-- Title IDs are 1 (Titans), 2 (Shawshank), 3 (Dark Knight), etc.
INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_ID_SEQ.NEXTVAL, 'DVD', 1); -- 92: Remember the Titans [cite: 62]
INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_ID_SEQ.NEXTVAL, 'VHS', 1); -- 93: Remember the Titans [cite: 62]
INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_ID_SEQ.NEXTVAL, 'DVD', 2); -- 94: Shawshank
INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_ID_SEQ.NEXTVAL, 'DVD', 3); -- 95: Dark Knight
INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_ID_SEQ.NEXTVAL, 'DVD', 4); -- 96: Forrest Gump
INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_ID_SEQ.NEXTVAL, 'DVD', 5); -- 97: Toy Story
INSERT INTO MEDIA (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (MEDIA_ID_SEQ.NEXTVAL, 'DVD', 6); -- 98: Interstellar

-- 5. RENTAL_HISTORY (Sample, need 4 rows, MEDIA_ID/CUSTOMER_ID must match)
-- We will make ONE rental (media 93) have a NULL return date
-- This is so our TITLE_UNAVAIL view will work!
INSERT INTO RENTAL_HISTORY (MEDIA_ID, RENTAL_DATE, CUSTOMER_ID, RETURN_DATE)
VALUES (92, TO_DATE('19-SEP-2010', 'DD-MON-YYYY'), 101, TO_DATE('20-SEP-2010', 'DD-MON-YYYY'));
INSERT INTO RENTAL_HISTORY (MEDIA_ID, RENTAL_DATE, CUSTOMER_ID, RETURN_DATE)
VALUES (94, TO_DATE('01-OCT-2024', 'DD-MON-YYYY'), 102, TO_DATE('05-OCT-2024', 'DD-MON-YYYY'));
INSERT INTO RENTAL_HISTORY (MEDIA_ID, RENTAL_DATE, CUSTOMER_ID, RETURN_DATE)
VALUES (96, TO_DATE('10-NOV-2024', 'DD-MON-YYYY'), 101, TO_DATE('12-NOV-2024', 'DD-MON-YYYY'));
INSERT INTO RENTAL_HISTORY (MEDIA_ID, RENTAL_DATE, CUSTOMER_ID, RETURN_DATE)
VALUES (93, TO_DATE('15-NOV-2024', 'DD-MON-YYYY'), 103, NULL); -- NOT RETURNED YET!

-- 6. STAR_BILLINGS (Sample, need 4 rows, ACTOR_ID/TITLE_ID must match)
-- Actor IDs: 1001 (Pitt), 1002 (Denzel), 1003 (Freeman), 1004 (Hanks)
-- Title IDs: 1 (Titans), 2 (Shawshank), 3 (Dark Knight), 4 (Gump)
INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS)
VALUES (1002, 1, 'Main Coach'); -- Denzel in Remember the Titans
INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS)
VALUES (1003, 2, 'Main supporting role'); -- Freeman in Shawshank
INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS)
VALUES (1004, 4, 'Lead Role'); -- Hanks in Forrest Gump
INSERT INTO STAR_BILLINGS (ACTOR_ID, TITLE_ID, COMMENTS)
VALUES (1004, 5, 'Voice of Woody'); -- Hanks in Toy Story


-- "Run a SELECT * for each table." 
SELECT * FROM CUSTOMERS;
SELECT * FROM MOVIES;
SELECT * FROM ACTORS;
SELECT * FROM MEDIA;
SELECT * FROM RENTAL_HISTORY;
SELECT * FROM STAR_BILLINGS;


-- Section 16, Task 6: Create an index 
CREATE INDEX IDX_CUST_LAST_NAME ON CUSTOMERS(LAST_NAME);

-- Query data dictionary for the index 
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'IDX_CUST_LAST_NAME';


-- Section 16, Task 7: Create a synonym 
CREATE SYNONYM TU FOR TITLE_UNAVAIL;

-- Query data dictionary for the synonym
SELECT SYNONYM_NAME, TABLE_NAME
FROM USER_SYNONYMS
WHERE SYNONYM_NAME = 'TU';

-- Print a SELECT * from the synonym 
-- This should now show 1 result (Media 93, "Remember the Titans")
-- because we added an unreturned rental.
SELECT * FROM TU;